### ISSUE TITLE
bash autocomple generator

### ISSUE THREAD

**Issue by basriyasin** [man-tools/man-tools#1]
bash auto complete is very handy to save time on typing and can be more user interactive as displaying what options are available for those program, but creating an auto completion is such a hard work and unfortunately i could not found any of generator which doesn't depends on a specific language e.g golang, python, etc.

why don't we have a generator which not depends on a programming language e.g i want to create an auto completion for my standalone bash script which doesn't have any manual page or some fancy feature like that? well the current solution is creating auto completion our self using complex bash syntax for instance: [Creating a bash completion script tutorial](https://iridakos.com/tutorials/2018/03/01/bash-programmable-completion-tutorial.html)

```bash
#/usr/bin/env bash
_dothis_completions()
{
  if [ "${#COMP_WORDS[@]}" != "2" ]; then
    return
  fi

  local commands_number=${DOTHIS_COMPLETION_COMMANDS_NUMBER:-50}
  local IFS=$'\n'
  local suggestions=($(compgen -W "$(fc -l -$commands_number | sed 's/\t//')" -- "${COMP_WORDS[1]}"))

  if [ "${#suggestions[@]}" == "1" ]; then
    local number="${suggestions[0]/%\ */}"
    COMPREPLY=("$number")
  else
    for i in "${!suggestions[@]}"; do
      suggestions[$i]="$(printf '%*s' "-$COLUMNS"  "${suggestions[$i]}")"
    done

    COMPREPLY=("${suggestions[@]}")
  fi
}

complete -F _dothis_completions dothis
```

<br/><br/><br/>
how about make it easy to build and more readable to maintain e.g using `yaml` extension to tell bash what is our program menu looks like with the following format
```yaml
program_name:
  sub_menu_1:
    sub_menu_1_1:
      sub_menu_1_1_1: ~ # end of command, no args needed anymore
    sub_menu_1_2:
      -flag-1: ~ # end of command, no args needed anymore
      -flag-2:
        ~: # -- (dynamic) - suggest file name as next arguments
          exec: "ls -p | grep -v /"

  sub_menu_2:
    ~: # -- (dynamic) - suggest file name as next arguments
      exec: "ls -p | grep -v /"

  # program flags
  -flag-1:
    ~: # -- (dynamic) - suggest folder name as flag value
      exec: "ls -p | grep /"
  -flag-2: ~ # -- no argument needs

  ~: # -- (dynamic) - suggest all file and folder on / directory
    exec: "ls /"
```
<br/><br/><br/>
example with `go` program
```yaml
go:
  build:
    -o:
      ~:
        # suggest all executable file
        exec: "ls -F | grep '*$' | cut -d '*' -f1"
  run:
    ~: # suggest all file with .go extension
      exec: "ls *go"
  version: ~
```
<br/><br/><br/>
example with custum script called `teleport`
```yaml
teleport:
  login:
    staging: ~
    production: ~
  ssh:
    ~: # suggest list of all nodes on current environtment
      exec: "teleport nodes $(teleport current-environtment)"
  nodes:
    production: ~
    staging: ~
  current-environtment: ~

```
